# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meisser Economics
email: luzius@meissereconomics.com
name: Meisser Economics
description: > # this means to ignore newlines until "baseurl:"
  Meisser Economics is a boutique economic and financial research firm
  applying methods of modern software engineering to build better economic
  models. Markets are recognized as interfaces between economic agents,
  whose behavior is independently specified and simulated. This results in
  versatile agent-based models that are fundamentally algorithmic, unlike
  traditional equation-based models that are fundamentally mathematical and
  monolithic.
gems: [jekyll-paginate,jekyll-feed]
paginate: 10
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meissereconomics.com" # the base hostname & protocol for your site
twitter_username: luzius
github_username:  meisserecon

# Build settings
markdown: kramdown
